---
# tasks file for memoryleak.dockerfile
- name: Include stat tasks
  include: "stat.yml"
  tags:
    - include
    - stat
    - dirs

- name: "Create Dockerfile for {{ dockerfile_repository }}/{{ dockerfile_name }}:{{ dockerfile_tag }}"
  template:
    dest: "{{ dockerfile_build_dir }}/Dockerfile"
    lstrip_blocks: true
    mode: 0755
    src: "Dockerfile.j2"
    trim_blocks: trim
  tags:
    - template
    - dockerfile
    - docker

- name: "Build Dockerfile for {{ dockerfile_repository }}/{{ dockerfile_name }}:{{ dockerfile_tag }}"
  docker_image:
    build:
      path: "{{ dockerfile_build_dir }}"
      pull: false
      nocache: true
      rm: true
    source: "build"
    force_source: true
    force_tag: false
    name: "{{ dockerfile_repository }}/{{ dockerfile_name }}"
    tag: "{{ dockerfile_tag }}"
    state: present

  tags:
    - docker_image
    - dockerfile

- name: Push image to registry
  docker_image:
    source: "local"
    name: "{{ dockerfile_repository }}/{{ dockerfile_name }}"
    push: true
    repository: "{{ dockerfile_registry }}/{{ dockerfile_repository }}/{{ dockerfile_name }}"
    state: present
    tag: "{{ dockerfile_tag }}"
  tags:
    - docker_image
    - dockerfile
  when: dockerfile_push
